### ISSUE TITLE
TemplateDoesNotExist at for hand picked product list.

### ISSUE THREAD

**Issue by DGathagu** [django-oscar/django-oscar-promotions#14]
I just installed promotions and i get an error template does not exist at **TemplateDoesNotExist at /dashboard/promotions/create/handpickedproductlist/** 
![Capture](https://user-images.githubusercontent.com/24543234/73154086-39d36600-40e7-11ea-9e99-0d1e79a26528.JPG)

What im i doing wrong?

**Comment by solarissmoke** [comment]
This looks like a bug in the template - will fix shortly.

**Comment by DGathagu** [comment]
Hope its fixed soon, please also update the pypi package to save other devs the pain of cloning the repo.
