### ISSUE TITLE
Oscar 2.0 support missing

### ISSUE THREAD

**Issue by zahessi** [django-oscar/django-oscar-promotions#5]
This app has been removed in Oscar 2.0, but support for that version has not been added. I can see that there is a pull request from the forked repository, and it is relevantly fresh but has not been updated since September, 20.

Could you look into this issue more closely? There still are apps which have been build on top of `promotions` as well and lack of support for Oscar 2.0 makes the migration process a lot harder.

**Comment by solarissmoke** [comment]
The master branch in this repo is now compatible with Oscar 2, and we'll put a beta release on PyPi next week. Thanks.
